#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Source shared library
# ---------------------------------------------------------------------------

_common_lib="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/install_common.sh"
if [[ ! -f "$_common_lib" ]]; then
  printf 'ERROR: Shared library not found: %s\n' "$_common_lib" >&2
  exit 1
fi
# shellcheck disable=SC1090
source "$_common_lib"

# ---------------------------------------------------------------------------
# Configure
# ---------------------------------------------------------------------------

usage() {
  cat <<'EOF'
usage: install/configure_ros_devkit.sh [--agent codex|claude|pi|custom] [--namespace-root PATH] [--skill-root PATH] [--force]

Configure ros-devkit to dispatch commands from an installed ROS2 namespace root.

Examples:
  install/configure_ros_devkit.sh --agent codex
  install/configure_ros_devkit.sh --agent claude
  install/configure_ros_devkit.sh --agent pi
  install/configure_ros_devkit.sh --agent custom --namespace-root /path/to/skills/ros2

Deprecated:
  --skill-root remains an alias for --namespace-root.
EOF
}

agent=""
namespace_root=""
force=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent)
      [[ $# -ge 2 ]] || die "--agent requires a value"
      agent="$2"
      shift 2
      ;;
    --namespace-root)
      [[ $# -ge 2 ]] || die "--namespace-root requires a value"
      namespace_root="$2"
      shift 2
      ;;
    --skill-root)
      [[ $# -ge 2 ]] || die "--skill-root requires a value"
      log "WARNING: --skill-root is deprecated; use --namespace-root instead."
      namespace_root="$2"
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

if [[ -z "$agent" ]]; then
  if [[ ! -r /dev/tty || ! -w /dev/tty ]]; then
    die "Interactive configuration requires a TTY. Pass --agent codex|claude|pi, or --agent custom --namespace-root PATH."
  fi

  print_agent_menu /dev/tty
  agent="$(prompt_tty "Agent [codex/claude/pi/custom]: ")"
fi

normalize_agent

if [[ "$agent" != "custom" ]]; then
  default_root="$(agent_skill_root_for "$agent")/$NAMESPACE"
else
  default_root=""
fi

if [[ -z "$namespace_root" ]]; then
  namespace_root="$default_root"
fi

if [[ -z "$namespace_root" ]]; then
  die "--agent custom requires --namespace-root PATH"
fi

namespace_root="$(expand_path "$namespace_root")"

required_script="$namespace_root/scripts/description_scaffold_lib/__main__.py"
if [[ "$force" -eq 0 && ! -f "$required_script" ]]; then
  die "Missing required script: $required_script
Use --force to write config before installing skills."
fi

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
config_dir="$config_home/ros-devkit"
config_file="$config_dir/config.env"

mkdir -p "$config_dir"
{
  echo "# Generated by install/configure_ros_devkit.sh"
  printf "ROS_DEVKIT_AGENT=%q\n" "$agent"
  printf "ROS_DEVKIT_SKILL_ROOT=%q\n" "$namespace_root"
} > "$config_file"

log "Configured ros-devkit"
log "Agent          : $agent"
log "Namespace root : $namespace_root"
log "Config file    : $config_file"
