#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
usage: scripts/configure_ros_devkit.sh [--agent codex|claude|pi|custom] [--namespace-root PATH] [--skill-root PATH] [--force]

Configure ros-devkit to dispatch commands from an installed ROS2 namespace root.

Examples:
  scripts/configure_ros_devkit.sh --agent codex
  scripts/configure_ros_devkit.sh --agent claude
  scripts/configure_ros_devkit.sh --agent pi
  scripts/configure_ros_devkit.sh --agent custom --namespace-root /path/to/skills/ros2

Deprecated:
  --skill-root remains an alias for --namespace-root.
EOF
}

agent=""
namespace_root=""
force=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --agent requires a value" >&2
        exit 2
      fi
      agent="$2"
      shift 2
      ;;
    --namespace-root)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --namespace-root requires a value" >&2
        exit 2
      fi
      namespace_root="$2"
      shift 2
      ;;
    --skill-root)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --skill-root requires a value" >&2
        exit 2
      fi
      echo "WARNING: --skill-root is deprecated; use --namespace-root instead." >&2
      namespace_root="$2"
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$agent" ]]; then
  echo "Select the installed ROS2 namespace root to configure:"
  echo "  1) codex  - \$HOME/.codex/skills/ros2"
  echo "  2) claude - \$HOME/.claude/skills/ros2"
  echo "  3) pi     - \$HOME/.pi/agent/skills/ros2"
  echo "  4) custom - provide --namespace-root PATH"
  printf "Agent [codex/claude/pi/custom]: "
  read -r agent
fi

case "$agent" in
  1)
    agent="codex"
    ;;
  2)
    agent="claude"
    ;;
  3)
    agent="pi"
    ;;
  4)
    agent="custom"
    ;;
esac

case "$agent" in
  codex)
    default_root="$HOME/.codex/skills/ros2"
    ;;
  claude)
    default_root="$HOME/.claude/skills/ros2"
    ;;
  pi)
    default_root="$HOME/.pi/agent/skills/ros2"
    ;;
  custom)
    default_root=""
    ;;
  *)
    echo "ERROR: Unsupported agent: $agent" >&2
    exit 2
    ;;
esac

if [[ -z "$namespace_root" ]]; then
  namespace_root="$default_root"
fi

if [[ -z "$namespace_root" ]]; then
  echo "ERROR: --agent custom requires --namespace-root PATH" >&2
  exit 2
fi

case "$namespace_root" in
  "~")
    namespace_root="$HOME"
    ;;
  "~/"*)
    namespace_root="$HOME/${namespace_root#~/}"
    ;;
esac

required_script="$namespace_root/description-scaffold/scripts/description_scaffold.py"
if [[ "$force" -eq 0 && ! -f "$required_script" ]]; then
  echo "ERROR: Missing required v1 script:" >&2
  echo "  $required_script" >&2
  echo "Use --force to write config before installing skills." >&2
  exit 1
fi

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
config_dir="$config_home/ros-devkit"
config_file="$config_dir/config.env"

mkdir -p "$config_dir"
{
  echo "# Generated by scripts/configure_ros_devkit.sh"
  printf "ROS_DEVKIT_AGENT=%q\n" "$agent"
  printf "ROS_DEVKIT_SKILL_ROOT=%q\n" "$namespace_root"
} > "$config_file"

echo "Configured ros-devkit"
echo "Agent          : $agent"
echo "Namespace root : $namespace_root"
echo "Config file    : $config_file"
